# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebf557270c91e5d7c66e8b7fd5bf5738"
name = "practice-app"
handle = "practice-app-114"
application_url = "https://compounds-receipt-legs-finances.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nogor-test-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://compounds-receipt-legs-finances.trycloudflare.com/auth/callback",
  "https://compounds-receipt-legs-finances.trycloudflare.com/auth/shopify/callback",
  "https://compounds-receipt-legs-finances.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
